# App-level execution and configuration
app {
  fhirServer = "http://localhost:8080/fhir"
  outputDir = "./out"
  jobType = "survey"
  format = "csv"
  runMode = "json"

  # Pointers to the metadata configuration files
  paths {
    json = "src/main/resources/config.json"
    excel = "src/main/resources/config.xlsx"
    htmlTemplate = "src/main/resources/form.html"
  }

  # FDP Connection Config (updated through here or cli parameters)
  fdp {
    url = ""
    email = "albert.einstein@example.com"
    password = "password"
  }
}

# Don't touch this - This sets up the overloaded spark-on-fhir application config
spark-on-fhir {
  akka {
    actor {
      provider = "local"
    }
    client {
      user-agent-header = akka-http/${akka.http.version}
      connecting-timeout = 10s
      idle-timeout = 60 s
    }
  }
}